# Generated by Django 4.1.3 on 2023-01-02 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_pv_post_uv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='desc',
            field=models.TextField(verbose_name='摘要'),
        ),
    ]
